/**
 * SNAPSHOT of workflow-service's dynasty word list (`src/lib/workflow-dynasty-signature-name.ts` `WORDS`,
 * origin/main 534eb726). Owner rule 2026-10-10: no catalogue name (sales funnel, pipe, sales path) may share a
 * word with a workflow's dynasty name, so every family pool is filtered against this list
 * (`lib/catalogue-names.ts`) and the guard test fails on any overlap. workflow-service only APPENDS words;
 * re-copy this list when it does (a word added there after a name was given here stays given here).
 */
export const WORKFLOW_DYNASTY_WORDS: readonly string[] = [
  "andromeda", "orion", "cassiopeia", "lyra", "vega", "sirius", "polaris", "altair", "rigel", "deneb",
  "antares", "arcturus", "betelgeuse", "capella", "canopus", "procyon", "aldebaran", "spica", "regulus",
  "fomalhaut", "achernar", "bellatrix", "mintaka", "alnilam", "alnitak", "mizar", "alcor", "dubhe", "merak",
  "alioth", "sequoia", "baobab", "cypress", "juniper", "cedar", "maple", "willow", "birch", "aspen",
  "magnolia", "acacia", "banyan", "redwood", "hemlock", "linden", "sycamore", "alder", "hazel", "laurel",
  "myrtle", "oleander", "wisteria", "jasmine", "orchid", "dahlia", "peony", "lotus", "iris", "azalea",
  "camellia", "obsidian", "quartz", "onyx", "jade", "topaz", "opal", "garnet", "zircon", "beryl", "pyrite",
  "agate", "jasper", "basalt", "granite", "marble", "slate", "feldspar", "mica", "cobalt", "titanium",
  "chromium", "rhodium", "iridium", "osmium", "bismuth", "galena", "calcite", "dolomite", "gypsum", "flint",
  "avalon", "olympus", "elysium", "arcadia", "valhalla", "asgard", "atlantis", "eldorado", "utopia",
  "shangri-la", "camelot", "hyperion", "lemuria", "midgard", "nirvana", "zion", "eden", "thule", "lyonesse",
  "ithaca", "colchis", "delphi", "knossos", "mycenae", "thebes", "carthage", "persepolis", "palmyra",
  "petra", "angkor", "phoenix", "griffin", "falcon", "osprey", "condor", "albatross", "peregrine", "kestrel",
  "merlin", "harrier", "heron", "crane", "pelican", "cormorant", "kingfisher", "nightingale", "skylark",
  "wren", "swift", "raven", "panther", "jaguar", "leopard", "lynx", "ocelot", "cheetah", "gazelle", "impala",
  "oryx", "ibex", "nautilus", "triton", "nereid", "coral", "tempest", "tsunami", "monsoon", "maelstrom",
  "cascade", "torrent", "fjord", "lagoon", "atoll", "reef", "delta", "estuary", "rapids", "geyser",
  "glacier", "iceberg", "tundra", "permafrost", "aurora", "boreal", "solstice", "equinox", "zenith", "nadir",
  "meridian", "horizon", "summit", "pinnacle", "ridge", "plateau", "mesa", "canyon", "ravine", "caldera",
  "crater", "volcano", "fumarole", "tectonic", "moraine", "cirque", "escarpment", "butte", "bluff",
  "promontory", "archipelago", "isthmus", "peninsula", "strait", "channel", "basin", "watershed",
  "tributary", "confluence", "headwater", "nebula", "pulsar", "quasar", "nova", "cosmos", "stellar", "lunar",
  "solar", "astral", "celestial", "twilight", "dusk", "dawn", "daybreak", "nightfall", "starlight",
  "moonbeam", "sunburst", "rainbow", "prism", "spectrum", "halo", "corona", "nimbus", "cirrus", "stratus",
  "cumulus", "zephyr", "mistral", "sirocco", "carbon", "silicon", "argon", "neon", "helium", "lithium",
  "sodium", "cesium", "strontium", "barium", "radium", "thorium", "uranium", "neptunium", "plutonium",
  "curium", "fermium", "einsteinium", "mendelevium", "nobelium", "lawrencium", "rutherford", "seaborg",
  "bohrium", "hassium", "meitnerium", "darmstadt", "roentgen", "copernicium", "flerovium", "crimson",
  "scarlet", "vermilion", "amber", "saffron", "ochre", "sienna", "umber", "cerulean", "azure", "indigo",
  "violet", "magenta", "cerise", "carmine", "burgundy", "maroon", "teal", "turquoise", "emerald", "viridian",
  "chartreuse", "olive", "khaki", "ivory", "pearl", "silver", "platinum", "bronze", "allegro", "adagio",
  "andante", "crescendo", "fortissimo", "pianissimo", "staccato", "legato", "vibrato", "tremolo", "cadenza",
  "fugue", "sonata", "prelude", "nocturne", "requiem", "serenade", "overture", "symphony", "concerto",
  "aria", "ballad", "etude", "rondo", "scherzo", "minuet", "bolero", "tango", "waltz", "mazurka", "spartan",
  "athenian", "roman", "viking", "samurai", "centurion", "gladiator", "pharaoh", "sultan", "emperor",
  "monarch", "sentinel", "guardian", "herald", "vanguard", "pioneer", "voyager", "navigator", "explorer",
  "pathfinder", "trailblazer", "frontier", "outpost", "citadel", "fortress", "bastion", "rampart", "parapet",
  "battlement", "watchtower", "apex", "vertex", "nexus", "cipher", "axiom", "theorem", "paradox", "enigma",
  "quantum", "vector", "matrix", "tensor", "scalar", "fractal", "helix", "spiral", "vortex", "flux", "pulse",
  "surge", "catalyst", "echo", "resonance", "harmony", "cadence", "rhythm", "tempo", "momentum", "velocity",
  "blossom", "harvest", "frost", "ember", "kindle", "spark", "blaze", "flame", "inferno", "pyre", "beacon",
  "lantern", "lighthouse", "compass", "anchor", "rudder", "helm", "keel", "mast", "bowsprit", "starboard",
  "portside", "leeward", "windward", "current", "drift", "voyage", "odyssey",
];
