CREATE TABLE IF NOT EXISTS "workflow_leg_assignments" (
	"feature_slug" text NOT NULL,
	"leg_key" text NOT NULL,
	"workflow_dynasty_slug" text NOT NULL,
	"state" text NOT NULL,
	"decided_by" text NOT NULL,
	"decided_at" timestamp with time zone DEFAULT now() NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "workflow_leg_assignments_state_check" CHECK ("state" IN ('active', 'deprecated'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uniq_workflow_leg_assignments" ON "workflow_leg_assignments" USING btree ("feature_slug","leg_key","workflow_dynasty_slug");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workflow_leg_assignment_changes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"feature_slug" text NOT NULL,
	"leg_key" text NOT NULL,
	"workflow_dynasty_slug" text NOT NULL,
	"from_state" text,
	"to_state" text NOT NULL,
	"decided_by" text NOT NULL,
	"decided_at" timestamp with time zone DEFAULT now() NOT NULL,
	"note" text
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_workflow_leg_assignment_changes_key" ON "workflow_leg_assignment_changes" USING btree ("feature_slug","leg_key","workflow_dynasty_slug","decided_at");
--> statement-breakpoint
-- SEED: every workflow dynasty that has ALREADY served at least one lead on a campaign performing the leg
-- (lead-service leads_campaigns.served_at, joined to campaign-service campaigns.leg_key, versions folded
-- into their dynasty via workflow-service), measured in prod 2026-09-27. All ACTIVE; nothing deprecated
-- (owner's decision). Campaigns stating no leg are ignored.
INSERT INTO "workflow_leg_assignments" ("feature_slug", "leg_key", "workflow_dynasty_slug", "state", "decided_by", "note") VALUES
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-cassiopeia', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 3 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-cesium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 5 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-condor', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 4 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-emperor', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 7 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-fortissimo', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 84 lead(s) on this leg, last 2026-08-24'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-linden', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 3 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-pyrite', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 3 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-rampart', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 7 lead(s) on this leg, last 2026-08-25'),
	('feedback-request-cold-email-outreach', 'start_to_conversation', 'feedback-request-cold-email-outreach-sodium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 3 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-alcor', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 17 lead(s) on this leg, last 2026-05-25'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-alioth', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 537 lead(s) on this leg, last 2026-09-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-allegro', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 314 lead(s) on this leg, last 2026-08-29'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-alnitak', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 939 lead(s) on this leg, last 2026-05-17'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-arcadia', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 435 lead(s) on this leg, last 2026-08-12'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-atoll', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 143 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-azalea', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 3628 lead(s) on this leg, last 2026-09-27'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-ballad', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2487 lead(s) on this leg, last 2026-09-25'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-baobab', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 391 lead(s) on this leg, last 2026-09-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-bolero', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 17 lead(s) on this leg, last 2026-04-21'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-bronze-2', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2353 lead(s) on this leg, last 2026-05-20'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-calcite', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 281 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-camellia', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 325 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-cascade', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 149 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-catalyst', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 154 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-cerulean', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2019 lead(s) on this leg, last 2026-09-12'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-cirque', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 941 lead(s) on this leg, last 2026-05-12'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-colchis', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 287 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-dawn', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 166 lead(s) on this leg, last 2026-07-16'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-delphi', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 148 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-dubhe', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 56 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-eden', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 212 lead(s) on this leg, last 2026-05-01'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-granite', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 336 lead(s) on this leg, last 2026-08-12'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-helium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 261 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-helm', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 376 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-isthmus', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 29 lead(s) on this leg, last 2026-05-25'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-legato', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2883 lead(s) on this leg, last 2026-06-28'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-lithium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 12288 lead(s) on this leg, last 2026-09-19'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-lyonesse', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 127 lead(s) on this leg, last 2026-09-09'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-maelstrom', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 130 lead(s) on this leg, last 2026-09-09'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-moraine', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 319 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-nimbus', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 398 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-nobelium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 243 lead(s) on this leg, last 2026-08-29'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-nocturne', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 56 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-osprey', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 153 lead(s) on this leg, last 2026-09-17'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-pelican', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1272 lead(s) on this leg, last 2026-08-03'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-permafrost', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2204 lead(s) on this leg, last 2026-09-26'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-rampart', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1962 lead(s) on this leg, last 2026-09-16'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-rudder', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 319 lead(s) on this leg, last 2026-08-31'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-tango', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 311 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-tectonic', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1295 lead(s) on this leg, last 2026-07-03'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-thule', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 294 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-trailblazer', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 465 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-vector', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 284 lead(s) on this leg, last 2026-07-29'),
	('sales-cold-email-outreach', 'start_to_conversation', 'sales-cold-email-outreach-wisteria', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 179 lead(s) on this leg, last 2026-08-24'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-allegro', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 15 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-atlantis', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2 lead(s) on this leg, last 2026-04-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-bastion', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 12 lead(s) on this leg, last 2026-04-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-bronze-2', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 488 lead(s) on this leg, last 2026-06-09'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-butte', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1 lead(s) on this leg, last 2026-04-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-calcite', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 11 lead(s) on this leg, last 2026-07-19'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-camellia', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1 lead(s) on this leg, last 2026-06-22'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-capella', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1 lead(s) on this leg, last 2026-04-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-cerulean', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 8 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-colchis', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 10 lead(s) on this leg, last 2026-07-07'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-dawn', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 488 lead(s) on this leg, last 2026-09-15'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-dubhe', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 6 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-fomalhaut', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1 lead(s) on this leg, last 2026-04-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-legato', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1038 lead(s) on this leg, last 2026-09-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-lithium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 3 lead(s) on this leg, last 2026-06-06'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-lyonesse', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 332 lead(s) on this leg, last 2026-09-27'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-maelstrom', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 129 lead(s) on this leg, last 2026-09-27'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-nobelium', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 8 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-nocturne', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 13 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-osprey', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1498 lead(s) on this leg, last 2026-09-27'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-pelican', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 2324 lead(s) on this leg, last 2026-09-27'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-permafrost', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 1700 lead(s) on this leg, last 2026-09-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-rampart', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 4218 lead(s) on this leg, last 2026-09-27'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-rudder', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 11 lead(s) on this leg, last 2026-08-25'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-tectonic', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 41 lead(s) on this leg, last 2026-06-06'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-thule', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 9 lead(s) on this leg, last 2026-07-07'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-cold-email-outreach-vector', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 302 lead(s) on this leg, last 2026-09-14'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-email-cold-outreach-aldebaran', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 550 lead(s) on this leg, last 2026-03-22'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-email-cold-outreach-falcon', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 109 lead(s) on this leg, last 2026-03-24'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-email-cold-outreach-headwater', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 51 lead(s) on this leg, last 2026-03-17'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-email-cold-outreach-mintaka', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 113 lead(s) on this leg, last 2026-03-19'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-email-cold-outreach-pharaoh', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 8 lead(s) on this leg, last 2026-03-12'),
	('sales-cold-email-outreach', 'start_to_website_visit', 'sales-email-cold-outreach-viking', 'active', 'seed:served-a-lead-on-this-leg', 'seed: served 15 lead(s) on this leg, last 2026-03-20')
ON CONFLICT ("feature_slug", "leg_key", "workflow_dynasty_slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "workflow_leg_assignment_changes" ("feature_slug", "leg_key", "workflow_dynasty_slug", "from_state", "to_state", "decided_by", "note")
SELECT "feature_slug", "leg_key", "workflow_dynasty_slug", NULL, "state", "decided_by", "note" FROM "workflow_leg_assignments" WHERE "decided_by" = 'seed:served-a-lead-on-this-leg';
